version: '3.4'

services:
  budgetingapp:
    image: budgetingapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  postgres:
    container_name: budget-db
    image: postgres:13
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/data/postgres
      - postgresdbdata:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - authnet

  redis:
    container_name: budget-redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  redis-commander:
    container_name: budget-redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
volumes:
  postgresdata:
    driver: local
  postgresdbdata:
    driver: local
  redisdata:
    driver: local

networks:
  authnet:
    driver: bridge
